// ==UserScript==
// @name        web-standards-userscript
// @version     0.2.0
// @license     MIT
// @homepage    https://crashmax-dev.github.io/web-standards-userscript/
// @icon        https://www.google.com/s2/favicons?sz=64&domain=web-standards.ru
// @match       https://web-standards.ru/*
// @grant       GM_addStyle
// @updateURL   https://crashmax-dev.github.io/web-standards-userscript/web-standards-userscript.meta.js
// @downloadURL https://crashmax-dev.github.io/web-standards-userscript/web-standards-userscript.user.js
// ==/UserScript==

(function(){"use strict";function c(e,t,...a){const n=document.createElement(e);return t instanceof Node?n.append(t):typeof t=="string"?n.append(f(t)):Array.isArray(t)?n.append(...t):(Object.assign(n,t),Object.assign(n.style,t?.style)),n.append(...a),n}function f(e){return document.createTextNode(e)}class _{#e;#t;#a;#o;#n;constructor(t,a,n,r){this.#e=t,this.#t=a,this.#n=n,this.#a=o=>r?.encode?r.encode(o):JSON.stringify(o),this.#o=o=>r?.decode?r.decode(o):JSON.parse(o),this.has()||this.write(this.#t)}get initialValue(){return this.#t}get value(){try{const t=this.#n.getItem(this.#e);return t?this.#o(t):this.#t}catch(t){return console.error(t),this.#t}}write(t){t instanceof Function&&(t=t(this.value));try{this.#n.setItem(this.#e,this.#a(t))}catch(a){return console.error(a),this.#t}return t}has(){return this.#n.getItem(this.#e)!==null}reset(){this.write(this.#t)}}class b extends _{constructor(t,a,n){super(t,a,localStorage,n)}}const l=new b("podcast-options",[]);function g(e){return l.value.find(t=>t.id===e)}function u(e,t){l.write(a=>{const n=a.findIndex(r=>r.id===e);return n!==-1&&(a[n]={...a[n],...t}),a})}function v(e){l.write(t=>(t.push(e),t))}function k(e){const t=e.cloneNode(),a=c("div",{className:"player__container"}),n=c("input",{name:"player__playbackrate",type:"range",value:`${t.playbackRate}`,step:"0.25",min:"0.75",max:"2",oninput:()=>{const d=parseFloat(n.value);t.playbackRate=d,r.textContent=`${t.playbackRate}`}}),r=c("label",{className:"player__playbackrate-label",htmlFor:"player__playbackrate"},`${t.playbackRate}`);a.append(t,n,r),e.replaceWith(a);const o=location.pathname.split("/").filter(Boolean).pop();if(!o)return;const i={id:o,time:0,volume:.1},s=g(o);s||v(i),t.addEventListener("timeupdate",()=>{u(o,{time:t.currentTime})}),t.addEventListener("volumechange",()=>{u(o,{volume:t.volume})}),t.currentTime=s?.time??i.time,t.volume=s?.volume??i.volume}function p(e){return e=Math.abs(e),e>9?`${e}`:`0${e}`}function w(e){for(const t of l.value){const a=e.find(x=>x.textContent?.trim()===t.id);if(!a)continue;const n=t.time,r=Math.floor(n/3600),o=Math.floor((n-r*3600)/60),i=Math.floor(n-r*3600-o*60),s=`/ ${p(r)}:${p(o)}:${p(i)}`,d=c("span",s);a.appendChild(d),a.classList.add("visited")}}const O="",m=document.querySelector(".page__war");m&&m.remove();const h=document.querySelector(".podcast__player");h&&k(h);const y=Array.from(document.querySelectorAll(".podcast-preview__number"));y.length&&w(y),GM_addStyle("body,.article-card__photo,.links__icon,.blob__photo,.colors,img{filter:invert(1)}.header{background-color:#fff}.podcast__player{filter:initial}.podcast-preview__number.visited{color:#b8860b}.player__container{grid-column:1/-1;display:flex}.player__playbackrate-label{align-self:center;margin-left:4px;width:3rem}")})();
